apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-index
data:
  index.html: |
    <html>
    <head><title>Welcome</title></head>
    <body>
      <h1 style="text-align:center; color:blue;">Welcome to Kubernetes!!
On a high level. I am Tittled Devops engineer with over 6years in General IT experiences. I have supported different Govt projects that uses Agil develoment life circle in their project management. Supporting different application developers with their code deployment through manual proccess and Automated CICD pipelines using tools like; Ansible, jenkins, Github, and other integrated tools like Sonarqube and Nexus.

Through my expertise in linux and AWS cloud, I have used Terraform to provision and build out infratructure in AWS cloud using terraform modules and templates. I have managed and build out aws service; VPC and its component, S3, EC2, Security group, cloud front and more. With experience in linux administration and engineer, I hava helped in installing, configuring and troubleshoot applications in linux based virtual machines.

I am also experienced in monitoring and logging using tools like Prometheus, Grafana, and Graylog to ensure system reliability and performance. My ability to automate infrastructure management, streamline deployments, and support application teams has made me an essential part of DevOps-driven projects. With a strong foundation in Linux, cloud computing, and CI/CD pipelines, I continuously seek to optimize processes and enhance operational efficiency.

I have been notified of the contract end date, thats why I am seeking for New Opportunities.
</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: html
        configMap:
          name: httpd-index
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    app: httpd
spec:
  type: NodePort   # Change to LoadBalancer if your cluster supports it
  selector:
    app: httpd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080   # Optional, Kubernetes will auto-assign if omitted

